### ISSUE TITLE
ModuleNotFoundError: No module named 'requests' (Although everything was installed)

### ISSUE THREAD

**Issue by github-userx** [ltsdw/jpg-church-downloader#1]
`jpg-church-downloader$ python jpg-church-downloader.py https://jpg.church/a/albumxyz.C Traceback (most recent call last):  File "jpg-church-downloader.py", line 5, in <module>
    from requests import get, Session, Response
ModuleNotFoundError: No module named 'requests'`

requirements.txt wad successfully used/installed everything (even with sudo)

**Comment by ltsdw** [comment]
Hi, you don't need to install the dependencies with root.

I think that what is happening is that either the pip or python has different versions.
could you please tell me the output of both, `pip --version` and `python --version`, like:

```
$ pip --version
pip 22.1.2 from /usr/lib/python3.10/site-packages/pip (python 3.10)

$ python --version
Python 3.10.5
```

you could also explicit run both as so:

```
pip3.10 install -r requirements.txt

python3.10 jpg-church-downloader https://jpg.church/a/albumid
```

**Comment by github-userx** [comment]
Thanks! In the meantime I also found the cyberdrop-dl tool that also supports jpg church

https://github.com/Jules-WinnfieldX/CyberDropDownloader

**Comment by ltsdw** [comment]
Thank you, I think it was solved then?
If not, feel free to reopen it :)
